* Cooker Notes

** Deeper Games

A lot of life is superficial
- One axis is /Doing Chores/
      - Actions which are /Means To An End/
- One axis is /Light Play/ without serious intent
      - Pleasurable Entertainment
      - Rest, Relaxation, Vacation
      - Light socialization
- The main axis for me is the Deeper Games
      - Ongoing, unlimited Growth and Development: Cultivation
      - Increasing opportunities for high-quality lives for all people

My tribe is the people for whom the deeper games have the highest priority.

** What Do I Want?

I want all human beings to enjoy full material abundance and full spiritual
abundance. I dedicate my life to accelerating and managing our collective
transition from the obsolete scarcity paradigm to the extraordinary abundance
paradigm which is available.

** What might we want?

If it were possible and affordable to solve many of the most serious problems
impacting human beings and the Earth's ecosystems?  Would you care?

If it were possible and affordable, would you care about
- significant extension to healthy human lifetimes
      - human beings living healthy lives without aging?
- a post-scarcity world
      - all of life's important goods and services abundantly available
- protecting and restoring the Earth's environment
      - from side-effects of human activity

*** How might we get these things?

If you seriously care about any of these possibilities, there is one
avenue which could certainly make all of

Replication technologies
- Molecular Nanotechnology
- Advanced Genetic Biotech

** What more might you care about?

Many good things we imagine are more about human attitudes than about material
resources.

Take a look at the inventory of [[https://www.cnvc.org/training/resource/needs-inventory][Universal Needs]] of suggested by [[https://en.wikipedia.org/wiki/Marshall_Rosenberg][Marshall
Rosenberg]]'s NVC Model.

Which of these "needs" matter to you? What olther concerns matter to you?

[[https://en.wikipedia.org/wiki/Maslow%27s_hierarchy_of_needs][Abraham Maslow]] would suggest that the less material concerns are most easily
addressed when material needs are well handled.

Working together on shared concerns can be a powerful way to effect change - and
it is also a direct way to meet many of our needs involving connection with
others.
