* My Ambivalence Towards Entertainment

** Presenting My Case

I often feel like a /Stranger in a Strange Land/. Most people feel this way
sometimes. Yet we vary in the forms of our strangenesses. One of my deviations
from the norm is cognitive. I am an [[https://en.wikipedia.org/wiki/High-functioning_autism][Aspie]], a high-functioning person on the
Autistic Spectrum. Unlike many people on the Autistic Spectrum I lucked out, I'm
cognitively gifted. But also cognitively deviant. And as [[https://en.wikipedia.org/wiki/Temple_Grandin][Temple Grandin]] said,
"If you know one Aspie, you know /one/ Aspie!". We humans are all unique, even
identical twins. If there is a /typical Aspie/, I am not /him/ - I say /him/
because 90% of diagnosed Aspies are male.

One of the things which sometimes makes me feel like an alien is my ambivalence
towards popular entertainment. Most forms of popular entertainment either repel
me or only hold my interest briefly, leaving me feeling unsatisfied along with a
sense of having wasted that portion of my life. Most of my fellow humans seem to
have a much larger appetite for popular entertainment than I do and they seek it
out in many forms: Movies, TV, music, light reading, (watching rather than
playing) sports, (various forms of) inebriation, as well as social events and
romantic dalliance which rarely create long term relationships and indeed seem
designed not to create any depth of relationship at all. I am apparently /too
serious/. But what does that mean?

My favorite medium is the written word. I love to read and my tastes are
diverse. But I'm also very picky about what I read. I certainly like (in fact, I
pretty much require) that what I read is well written, that the author makes the
work come alive and doesn't annoy me with clumsiness. I am not indifferent to
that aspect of entertainment, I pretty much require it. Then why is
entertainment by itself insufficient? What else do I require?

A possibly relevant bit of context: I learned to read by being read to, usually
sitting in someone's lap with a book in my lap. No one explicitly taught me. By
the time the school system got around to trying to teach me how to read as a
conscious skill reading was already an automatic and effortless part of my life.
I learned how to read just as I learned my native language, through exposure
when young. I am a native reader.

As a child I read everything in the house, but when I got access to the small
library at my elementary school I discovered science and science fiction,
neither of which existed at home. These rapidly became my favorites! I liked the
science to be as advanced as I could follow without frustration, and the science
fiction to be rational while maximally stimulating and stretching my
imagination.

In my school days my teachers were unimpressed by what I liked to read. They had
nothing to say about the science and they denigrated the science fiction as
being /escapist literature/. They recommended and often required that I read
/serious literature/. Tragic realism. People in ordinary or challenging
circumstances, behaving conventionally (i.e. foolishly), getting the results you
would expect and suffering horribly as a consequence. The suffering was supposed
to be ennobling for the characters and vicariously enriching for the reader. I
find such stories horrible, partly because of my compassion with the character's
suffering and partly because of cringing at the vicarious experience of making
such poor decisions! I can certainly make, and have made such poor decisions,
but reading about other people being foolish doesn't make me feel better about
my own mistakes! But was my preferred fare any better? And what about what my
teachers viewed as the worst escapist literature, comic books? My elementary
school friend had collected a shoebox full and allowed me to read some. I found
them wonderful! And what about the other things I sometimes enjoyed reading,
such as my mother's college textbooks?

There's a quote by the brilliant author Neil Gaiman about how a book in which
the characters do not grow and develop as the book advances is not a very good
book. For me, a book in which I do not grow and advance by reading it is not a
very good book! Heinlein had one of his characters define a good book as one
which would reward you further when you reread it and a great book was one which
would reward you every time you reread it. I frequently reread some of my
favorite books with pleasure and enrichment!

Good books are magical. The imagination of the reader is not limited by the
imagination or expectation of the writer. Books are not linear: The reader can
speed up, slow down, jump around and review as they wish. Good books entice and
train the reader to be an active participant in the story. Movies and TV are
much less magical. They supply all the imagery and they move at a linear forced
pace. They train the audience to suppress their own thoughts and imagination
lest they miss something. Sadly, when people see a movie /inspired by a book/
they imagine that they've obtained the value of the book with less effort and
time. Yet I understand: If you haven't made reading automatic, the mechanics of
reading are tiring and interfere with full engagement with the content.

One of my teachers, Werner Erhard, said that the background mood of human beings
is resignation and despair. I didn't like to hear that and I almost don't relate
to it. Yes, I sometimes notice that I have a lot of underlying fear. Most of it
being fear of being persecuted because I'm different. Or fear of being stupid,
an all too real fear since my intelligence seems to fluctuate a great deal! Or
fear of having to face overwhelming circumstances without the solidarity and
assistance of my tribe. Of not having a tribe. I have a lot of underlying fear
which sometimes emerges and disables me for a time. But despair? I have a great
capacity for awareness and regeneration and despair does not persist very long
at a time.

I noticed when studying Romance languages, that the word for /fun/ often
translated as /diversion/. And in English we sometimes use "diverting" as a
synonym. Hmm, diversion from what? I often read promotional material on new
books. The advertisers extol the pleasure the reader will get from the
enthralling story, from the play of emotions, etc. contained within. Ugh, spare
me! The advertisers seem to think that I'm seeking diversion. A temporary escape
from my dreary life. Books as recreational drugs! When my life seems ordinary
and dreary, I certainly do want to escape that - by stepping out of whatever is
making it ordinary and back into my real life, which is extraordinary!

** Arguing Against and For My Case

*** Popular Culture Can Be Enlightening

My father, who was a professional Rocket Engineer and a gifted musician and
composer didn't understand why people read fiction, /since it isn't true/! I
know better, thanks to the work of my family exposing me early to a wide variety
of quality fiction.

Stories (whether made up out of whole cloth or based on (made up from) "real
events") can take you into the lives of other people, despite this coming from
the author's imagination. You get exposed to a great variety of the human
experience. You get an outside perspective on people like and unlike yourself.
You get the invaluable ability to see things from more than one perspective.
Good fiction is like the fantasy of telepathy and telepathic empathy made real.
I suspect that this powerful vicarious experience has helped me gain the decent
empathetic understanding of myself and others, despite being "on the spectrum".
And while I've mostly consumed stories through fiction - and mostly Science
Fiction at that - these benefits apply to all forms of storytelling, whether
auditory (podcasts), audiovisual (movies, TV, videos) or the written word - and
yes, it applies in abundance to the /Serious Literature/ which my teachers
wanted me to read more of - it was just a poor fit for me.

I was just reading on [[https://vox.com]] their article [[https://www.vox.com/culture/23387432/fall-2022-movie-releases-films][Here are 29 new movies to
get excited about]], and as I read the reviews I was excited about the richness of
the movies they were reviewing. Of course Vox is pretty high-brow compared to
the more popular news sources. I don't believe that these movies will sell as
well as the shallower, more formulaic offerings. Yet there is a continuum, and
the lighter fare prepares young people to be able to appreciate increasingly
sophisticated material. The best example I know of leveraging this continuum is
the /Harry Potter/ series.

J.K Rowling deliberately designed the /Harry Potter Series/ of books to
bootstrap children into being able to read sophisticated books. She started
starting with the primitive 2-dimensional wish fulfillment of /Harry Potter and
the Sorcerer's Stone/ which then hooks a young reader and motivates them to read
the slightly more advanced sequel, and so on. As the reader moves through the
series, they find themselves reading more complex (and longer) novels in which
none of the characters are wholly good or bad, all of them have understandable
inner lives which motivate their behavior, etc. Yet I wish that J.K Rowling had
never authorized the making of any of the movies after the first. The first
movie would have motivated children to read the books to learn more. Having a
whole series of movies with the same titles as the books deceives most children
(and naive adults) into thinking that they have anything like the same value,
that having watched the movie there was no /need/ to read the book. Alas, the
movies provide little of the value of the books.

When I was a child in the 1960s, popular movies and television seemed to be
mostly about propagating unthinking mainstream values. Thoughtful movies were
rare and usually unpopular, often only playing in a few "Art House" theaters in
a few big city locations. The cultural elite referred to television as the
/idiot box/, suitable only for babysitting children and to help adults unwind
from their stressful workday, after they'd lowered their IQ with a few drinks or
pills. While the majority of popular culture is still as vapid as [[https://en.wikipedia.org/wiki/Sturgeon%27s_law][Sturgeon's law]]
would predict, today's popular cultural fare seems to be better than what I grew
up with. It is more diverse in topics and perspective and tends to be
multi-layered - which is a good way of appealing to both the naive and
sophisticated consumers with the same product. Examples of this quality and
strategy are shows like /South Park/ and /The Simpson's/, where the surface
story is crude and banal, but the next layer down will reward the sophisticated
consumer with (a self-congratulatory belief in their moral and intellectual
superiority - whoops, no ...) insightful value. Learning to read below the banal
surface for deeper meaning is good for people's cognitive development and the
knowledge and wisdom they obtain is likely to stick better for the effort of
pulling it up.
