* Native Fluency

There is a huge difference in competence between skills which are fully
internalized vs. skills which require conscious thought to perform them.
Conscious engagement can facilitate internalization of skills and it can enrich
skills which have been well internalized. The way you go about it makes the
difference!

** Language Learning

American children are encouraged or required to study a foreign language in
school, usually after age 14. Not all schools use the same methods, but most use
a traditional top-down teaching method involving a great deal of memorizing
vocabulary and grammar rules and practicing examples in, e.g. repetition
substitution exercises. There is also a great deal of memorization of
conversational dialogs. After two or more years of such study, most of the
students have only rudimentary performance. It is also not well liked, with few
students continuing any longer than required.

Contrast that with the skills of children who grow up in an environment where
more than one language is used at home and in their peer community. Every single
such child achieves perfect fluency. We call them native speakers. Their
language skills are qualitatively as well as quantitatively different from
children who are taught through explicit top-down methods of instruction.

It is generally believed that native fluency cannot be routinely achieved
through classroom instruction and it is much more difficult or impossible for
older students to achieve native fluency.  Both of these beliefs are false.

There are teaching methods which routinely and reliably produce native or
near-native fluency in students of all ages in a modest amount of time. The US
Military runs immersion courses which achieve such in a few months. The methods
introduced by Leonard Newmark at UC San Diego in the late 1970s achieved such in
four academic quarters with no more than the usual amount of time in the
classroom and language lab.

Before exploring what makes the difference, we want to explore similar
differences in learning in other disciplines. We would especially like to know
whether there's something analogous to native fluency for other subjects which
is rarely achieved through traditional classroom plus homework instruction..

** Reading Fluency

Most children learn to read in school. Some children learn to read before school
without being explicitly taught.  How does this happen and how is it different?
I'll begin with my own story, which I've since learned is quite common.

When I was a child it was common for relatives to put me on their lap and a
children's book in my lap and read to me, with me being able to see any pictures
as well as the text. My relatives didn't try to teach me to read but after a few
months I was reading effortlessly. I was a native reader. I read everything in
the house, including stories, magazines, college textbooks, etc. with pleasure.

Most adult Americans struggle with tests of reading speed and comprehension.
Most Americans don't read for pleasure, it's a chore which they do when they
must. Many Americans say that reading much gives them a headache. Yet a
significant subset of Americans are avid readers. When I meet other avid
readers, I always ask them if they learned to read at home or at school. More
than half say they learned at home. Most children who are taught reading in
American schools do not become native readers of their own language!

Years later when my school teacher was teaching the class how to read, she sent
me to the special remedial reading class to get me out of her classroom during
reading instruction time. This turned out to be a blessing. English is not a
very phonetic language and like many native English readers, I was a "sight
reader", i.e. I simply recognized words by their appearance. At that time the
Phonics System was starting to be popular as a method for teaching English.
Phonics was the method used in that remedial class for struggling readers - and
me. I found it fascinating to learn the complex ways in which the sound pattern
of English is encoded in English spelling. Today the Phonics system is
controversial as a method for teaching English reading, but those criticisms
don't apply to me as for me it was simply enrichment.

** Mathland

Seymour Papert 
