* The Naturalism Fallacy Fallacy

Is microwave cooking bad? Is nuclear power evil? Are natural foods better for
you? How about organic foods? Raw foods? Is nature good? Is nature evil? If it
feels good, is it good? How do you feel about genetically modified organisms?

If something is natural, i.e. something which is an ancient feature of the
natural world and perhaps also a traditional part of some human culture, I
suggest we should be suspicious of it, suspicious of whether it's good for us.
The /Naturalism Fallacy/ tells us that something being /natural/ in no way
implies that it is /good/.

If an innovative new practice feels intuitively strange and unnatural, I suggest
we should be suspicious of whether it's good for us, even more than we would be
suspicious of something "natural" and "traditional". The /Precautionary
Principle/ tells us that something being /new/, /innovative/, /modern/,
/progressive/ or /scientific/ could easily have drawbacks compared to something
/time-tested/.

When people call something "natural" or "unnatural", what is this based on? For
some people, "natural" is anything which they feel comfortable with and
"unnatural" is anything which seems strange and unfamiliar, especially if it
makes them feel uncomfortable and maybe especially when they are unclear about
why. To a physicist, anything which is possible in this Universe is "natural"
and anything else is "unnatural". A biologist would consider an organism as
"natural" if it evolved in its current environment and perhaps "unnatural" (or
alien) if it is not in the environment where it evolved. Some biologists might
view a genetically modified organism as being in some sense "unnatural", but not
in a sense of being bad - they might consider some GMO organisms to be a source
of great benefit to humanity and to nature, e.g. a new food crop which is tasty,
nutritious and can be grown with less environmental impact than conventional
crops.
